### PR TITLE
[Feature] Body Detection + Tracking

### PR DESCRIPTION
**Pull request by TCVinNYC**
Add a more reliable way to track a user by tracking the body with the recognized face.

Should provide greater stability and reliablity compared to using a smaller fixed tracked object like a face.

Also testing smoother PTZ movement when tracking to keep the user in center instead of using the bounding boxes.

### CODE REVIEW

**Review by jcook03266 — COMMENTED** [review]
Major camera widget interface change from `shared_data=self.shared_camera_data` to `manager=self.manager`. Make sure all definitions are updated and no interface collisions are present.

**Review by jcook03266 — APPROVED** [review]
The new pose estimation functionality implementation looks good and is decoupled from the rest of the codebase, but further testing should be done in a live environment to make sure it performs properly. One minor improvement I'd suggest is in the`person_tracker` file, specifically the `process_frame` method, to reduce conditional statement nesting to improve readability.

**Review by jcook03266 — APPROVED** [review]

**Review by jcook03266 — APPROVED** [review]

**Comment by TCVinNYC** [comment]
Changes in this PR

- All PTZ Cameras move with dynamic speed using a quadratic easing function (ease in and out)
- Removed bounding boxes for moving PTZ cameras when tracking, in favor of a newer safe zone ellipse.
- Facial Recognition Process no longer removed frames (moved from Queue to List to store camera frames)
- Body Pose Estimation is a new Process (each camera has VideoStream, Facial Recognition, and Body Pose Processes)
- Body Pose Estimation is utilized for tracking over only relying on Facial Recognition boxes
- Shared Data variable is removed, in favor of a more efficient Queue system to share processing result data
- Slight code cleanup and simplified requirements.txt as well

**Comment by TCVinNYC** [comment]
forgot to merge lol

**Pull request merged**
